### ISSUE TITLE
Extending plugin architecture

### ISSUE THREAD

**Issue by wzorgdrager** [codefeedr/epoch-alignment#13]
The current plugin architecture is only able to compose a Flink stream and create a subject for it. Also this can only be run in a test, which makes the current usability quite limited.
I've been thinking about extending this:

---
**PluginJob**
- Can be compared to the current _AbstractPlugin_
- Holds 1 Flink job
- Has its own paralellism
- Has its own subject(type)
- Custom source and Kafka sink

**Plugin**
- Manages multiple PluginJobs
- Initializes and starts all PluginJobs in parallel (in their own environment)
- Is able to link the sink of one PluginJob as source of another PluginJob

Here a simple visualization/summary:
![pluginarchitecture](https://user-images.githubusercontent.com/2283622/35766136-51cd7966-08d2-11e8-8a38-8b2bf5598b3e.png)

---
I think this is the easiest setup in the current architecture since I can reuse parts of the AbstractPlugin class. An important feature useful for this setup would be a KafkaSink/KafkaSource which already converts the data into their (original) case classes (already mentioned in #11). 

Any ideas/comments/recommendations @nvankaam ?

**Comment by nvankaam** [comment]
I do agree it should be possible to create plugins that spawn multiple jobs. 

I am not sure however if we should make distinction between "PluginJobs" and "QueryJobs". We currently cannot run queries outside of tests either (because we just haven´t worked on deployment yet). The responsibilities mentioned for "PluginJob" are similar to the responsibilities of a "QueryJob". The only difference I currently see between a "QueryJob" and a "PluginJob" is that the plugin job takes data from external source(s), from which we do not have type-information, while a query takes data from Kafka topic(s)from which we have type-information in zookeeper.

So if you want to work on deployment, or being able to run jobs outside of unit tests, I would try to keep this generic for both query- and plugin- jobs. A "Plugin" then just exposes one or more "Jobs". These Jobs then expose Subject(Types). If we see the need to treat plugin jobs different from query jobs we can always branch them off later.

**Comment by nvankaam** [comment]
So I agree with you, if we just rename "PluginJob" to "Job". 😃
